# Generated by Django 5.1.6 on 2025-02-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='product',
            field=models.ManyToManyField(to='purchases.product'),
        ),
    ]
