# Generated by Django 5.1.6 on 2025-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchaserequest_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='product_quantities',
            field=models.JSONField(default=dict),
        ),
    ]
