# Generated by Django 5.1.6 on 2025-02-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchaserequest_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='product_quantities',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField()),
                ('required_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaserequest')),
            ],
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='products',
            field=models.ManyToManyField(through='purchases.PurchaseRequestItem', to='purchases.product'),
        ),
    ]
